### ISSUE TITLE
Debounce

### ISSUE THREAD

**Issue by PrismaPhonic** [jonhoo/vote.rs#5]
Have you considered using a debounce function to cut down on post requests made by fetch?

[debounce](https://underscorejs.org/#debounce)

I'd imagine that users might be quickly clicking and dragging their choices around.  The debounce delay time could be relatively long - like 2 seconds for instance - which should drastically cut down on post requests being made by fetch.  

If something like this sounds interesting to you I'd be happy to add it in and submit a PR.

**Comment by jonhoo** [comment]
Hmm, that's an interesting idea. I don't think it's all that much of a problem as it stands, but it seems like a good change, so I'd be happy to look at a PR :)

**Comment by PrismaPhonic** [comment]
I'm going to close this ticket - I tried playing around with it and sortable doesn't play nice with debounce.  There's probably a way to get them working well together but it doesn't seem like a high priority item for now.
